# http port set
server:
  port: 8484

spring:
  # File Size
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
             
  # Oracle Connect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
        
  # view resolver(Template -> JSP Use)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
# Mybatis
mybatis:
  # dto Location
  type-aliases-package: crud.crudProject.model
  # xml Location
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
